config/routes.rb
Xyz::Application.routes.draw do
  devise_for :users

  root 'homes#index'

  resources :homes
  resources :products
  resources :resources
  resources :customers
  resources :suppliers
  resources :sales

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :sales
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :product
  belongs_to :resource
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :ingredients
  has_many :resources, :through => :ingredients
  has_many :sales
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  has_many :ingredients
  has_many :products, :through => :ingredients
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :customer
  belongs_to :product
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @customers = Customer.all
  end

  def new
    @customer = Customer.new
  end

  def create    
    customer = Customer.new(customer_params)

    if customer.save
      notice = "Customer berhasil di buat."
    else
      notice = "Customer gagal di buat. Hubungi administrator."
    end
    redirect_to customers_path, :notice => notice
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    customer = Customer.find(params[:id])

    if customer.update_attributes(customer_params)
      notice = "customer berhasil di update."
    else
      notice = "customer gagal di update. Hubungi administrator."
    end
    redirect_to customers_path, :notice => notice
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :address, :phone)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
    @resources = Resource.all
  end

  def create
    product = Product.new(product_params)

    if product.save
      if params[:ingredients]
        params[:ingredients].each do |key, data|
          if data[:name]
            ingredient = Ingredient.new
            ingredient.product_id = product.id
            ingredient.resource_id = key
            ingredient.rate_percent = data[:rate_percent]
            ingredient.save
          end
        end
      end
      notice = "Product berhasil di buat."
    else
      notice = "Product gagal di buat. Hubungi administrator."
    end
    redirect_to products_path, :notice => notice
  end

  def edit
    @product = Product.find(params[:id])
    @resources = Resource.all
  end

  def update
    product = Product.find(params[:id])

    if product.update_attributes(product_params)
      notice = "Product berhasil di update."
    else
      notice = "Product gagal di update. Hubungi administrator."
    end
    redirect_to products_path, :notice => notice
  end


  private

  def product_params
    params.require(:product).permit(:name, :quantity, :price)
  end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @resources = Resource.all
  end

  def new
    @resource = Resource.new
  end

  def create    
    resource = Resource.new(resource_params)

    if resource.save
      notice = "Resource berhasil di buat."
    else
      notice = "Resource gagal di buat. Hubungi administrator."
    end
    redirect_to resources_path, :notice => notice
  end

  def edit
    @resource = Resource.find(params[:id])
  end

  def update
    resource = Resource.find(params[:id])

    if resource.update_attributes(resource_params)
      notice = "Resource berhasil di update."
    else
      notice = "Resource gagal di update. Hubungi administrator."
    end
    redirect_to resources_path, :notice => notice
  end

  private

  def resource_params
    params.require(:resource).permit(:name, :quantity)
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @sales = Sale.all
  end

  def new
    @sale = Sale.new
    @products = Product.all.collect{|x|[x.name, x.id]}
    @customers = Customer.all.collect{|x|[x.name, x.id]}
  end

  def create    
    sale = Sale.new(sale_params)

    if sale.save
      sale.product.update_attribute('quantity', (sale.product.quantity - sale.quantity))
      notice = "Sale berhasil di buat."
    else
      notice = "Sale gagal di buat. Hubungi administrator."
    end
    redirect_to sales_path, :notice => notice
  end

  def edit
    @sale = Sale.find(params[:id])
  end

  def update
    sale = Sale.find(params[:id])

    if sale.update_attributes(sale_params)
      notice = "Sale berhasil di update."
    else
      notice = "Sale gagal di update. Hubungi administrator."
    end
    redirect_to sales_path, :notice => notice
  end

  private

  def sale_params
    params.require(:sale).permit(:product_id, :customer_id, :date, :quantity, :total_price)
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @suppliers = Supplier.all
  end

  def new
    @supplier = Supplier.new
  end

  def create    
    supplier = Supplier.new(supplier_params)

    if supplier.save
      notice = "Supplier berhasil di buat."
    else
      notice = "Supplier gagal di buat. Hubungi administrator."
    end
    redirect_to suppliers_path, :notice => notice
  end

  def edit
    @supplier = Supplier.find(params[:id])
  end

  def update
    supplier = Supplier.find(params[:id])

    if supplier.update_attributes(supplier_params)
      notice = "Supplier berhasil di update."
    else
      notice = "Supplier gagal di update. Hubungi administrator."
    end
    redirect_to suppliers_path, :notice => notice
  end

  private

  def supplier_params
    params.require(:supplier).permit(:name, :address, :phone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def link_helper(name, control)
    name == control ? flag = true : flag = false

    if flag
      return 'active'
    else
      return ''
    end
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/customers/_form.html.erb
<%= form_for @customer, :url => url, :html => {:class => "form-horizontal col-sm-12 col-sm-offset-1"} do |f| %>
<br><br>
  <div class="form-group">
    <label for="customer_name" class="col-sm-2 control-label">Customer Name</label>
    <div class="col-sm-3">
      <%= f.text_field :name, :placeholder => "Enter Customer Name", :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label for="quantity" class="col-sm-2 control-label">Address</label>
    <div class="col-sm-3">
      <%= f.text_field :address, :placeholder => "Enter Customer Address", :class => "form-control" %>
    </div>
  </div> 

  <div class="form-group">
    <label for="quantity" class="col-sm-2 control-label">Phone</label>
    <div class="col-sm-3">
      <%= f.text_field :phone, :placeholder => "Enter Customer Phone", :class => "form-control" %>
    </div>
  </div>  

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-12">
      <%= f.submit 'Save', :class => "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1 class="page-header">Edit Customer</h1>
<%= render 'customers/form', :url => customer_path %>

app/views/customers/index.html.erb
<h1 class="page-header">Customer</h1>

<div class="form-group">
  <div class="col-sm-offset-1 col-sm-10">
    <%= link_to 'Add <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>'.html_safe, new_customer_path, :class => "btn btn-default" %>
    
    <div class="col-lg-4">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Search for...">
        <span class="input-group-btn">
          <button class="btn btn-default" type="button">
            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
          </button>
        </span>
      </div><!-- /input-group -->
    </div>

  </div>      
</div>
<div class="clearfix"></div>
<div class="table-responsive">
  <table class="table table-bordered">
    <caption></caption>
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Address</th>
        <th>Phone</th>
        <th>&nbsp;</th>
      </tr>
    </thead>
    <tbody>
      <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td><%= customer.name %></td>
          <td><%= customer.address %></td>
          <td><%= customer.phone %></td>
          <td>
            <%= link_to "Update", edit_customer_path(customer) %>
            &nbsp
            <a href="">Delete</a>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/customers/new.html.erb
<h1 class="page-header">Add Customer</h1>
<%= render 'customers/form', :url => customers_path %>

app/views/homes/index.html.erb
<h1 class="page-header"> Company Profile </h1>
<%= image_tag "logo3.jpg" %>
<br><br>
<p class="text-justify" style="font-family:times new roman; font-size:20"><b><u>Profil Perusahaan</u></b><br><br>
PT. XYZ merupakan perusahaan yang bergerak dalam bidang manufaktur untuk pembuatan bahan kimia tekstil.<br>
Perusahaan ini terletak di daerah Bandung dan telah berdiri selama 7 tahun.Perusahaan ini telah menjalin <br>
kerjasama dengan agen resmi di luar negeri, seperti Cina, India, dan Korea sebagai pemasok bahan baku dalam <br> 
pembuatan obat tekstil tersebut. Produk yang dihasilkan berupa bahan kimia tekstil yang biasa digunakan sebagai<br> 
pewarna dan pemutih kain. Bahan kimia yang di produksi dibuat untuk 3 jenis kain, yaitu kain katun, kain polister,<br>
dan kain nylon.</p>

<p1 class="text-justify" style="font-family:times new roman; font-size:20">
  <b><u>Visi Perusahaan</u></b>
  <br><br>
  Menjadi pilihan utama dalam bisnis bahan kimia pembantu proses tekstil.
</p1>

<br><br>

<p2 class="text-justify" style="font-family:times new roman; font-size:20">
  <b><u>Misi Perusahaan</u></b>
  <br><br>
  Untuk dikenal sebagai pembuat zat kimia tekstil berkualitas tinggi yang memberikan nilai tambah (bagi pelanggan kami)
  <br>
  dengan menggunakan seluruh talenta anggota-anggota dan pekerja-pekerja kami.
  <br>
</p2>

app/views/products/_form.html.erb
<%= form_for @product, :url => url, :html => {:class => "form-horizontal col-sm-12 col-sm-offset-1"} do |f| %>
<br><br>
  <div class="form-group">
    <label for="product_name" class="col-sm-2 control-label">Product Name</label>
    <div class="col-sm-3">
      <%= f.text_field :name, :placeholder => "Enter Product Name", :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label for="quantity" class="col-sm-2 control-label">Quantity</label>
    <div class="col-sm-3">
      <%= f.text_field :quantity, :placeholder => "Enter Product Quantity per KG", :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label for="price" class="col-sm-2 control-label">Price</label>
      <div class="col-sm-3">
        <div class="input-group">
          <div class="input-group-addon">Rp</div>
            <%= f.text_field :price, :placeholder => "Amount", :class => "form-control" %>
          <div class="input-group-addon">.00</div>
        </div>
      </div>
  </div>   

  <div class="form-group">
    <label for="lastname" class="col-sm-2 control-label">Ingredients</label>
    <div class="row">
      <div class="col-sm-5">
        <% @resources.each do |resource| %>
          <div>
            <label class="checkbox-inline">
              <%= check_box_tag "ingredients[#{resource.id}][name]", true, @product.resources.collect{|x|x.id}.include?(resource.id) %> <%= resource.name %>
            </label>
            <%= text_field_tag "ingredients[#{resource.id}][rate_percent]", "", :placeholder => "%" %>
          </div>
          <div class="clearfix"></div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-12">
      <%= f.submit 'Save', :class => "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1 class="page-header">Edit Product</h1>
<%= render 'products/form', :url => product_path %>

app/views/products/index.html.erb
<h1 class="page-header">Product</h1>

<div class="form-group">
  <div class="col-sm-offset-1 col-sm-10">
    <%= link_to 'Add <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>'.html_safe, new_product_path, :class => "btn btn-default" %>
    
    <div class="col-lg-4">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Search for...">
        <span class="input-group-btn">
          <button class="btn btn-default" type="button">
            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
          </button>
        </span>
      </div><!-- /input-group -->
    </div>

  </div>      
</div>
<div class="clearfix"></div>
<div class="table-responsive">
  <table class="table table-bordered">
    <caption></caption>
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Quantity</th>
        <th>Price</th>
        <th>&nbsp;</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.id %></td>
          <td><%= product.name %></td>
          <td><%= product.quantity %></td>
          <td><%= product.price %></td>
          <td>
            <%= link_to "Update", edit_product_path(product) %>
            &nbsp
            <a href="">Delete</a>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/products/new.html.erb
<h1 class="page-header">Add Product</h1>
<%= render 'products/form', :url => products_path %>

app/views/sales/_form.html.erb
<%= form_for @sale, :url => url, :html => {:class => "form-horizontal col-sm-12 col-sm-offset-1"} do |f| %>
<br><br>
  <div class="form-group">
    <label for="customer_name" class="col-sm-2 control-label">Date</label>
    <div class="col-sm-3">
      <div class='input-group date' id='datetimepicker1'>
        <%= f.text_field :date, :placeholder => "dd/mm/yy", :class => "form-control" %>
        <span class="input-group-addon">
          <span class="glyphicon glyphicon-calendar"></span>
        </span>
      </div>
    </div>
  </div>

  <div class="form-group">
    <label for="quantity" class="col-sm-2 control-label">Customer</label>
    <div class="col-sm-3">
      <%= f.select :customer_id, options_for_select(@customers), :class => "form-control" %>
    </div>
  </div> 
  <div class="form-group">
    <label for="quantity" class="col-sm-2 control-label">Product</label>
    <div class="col-sm-3">
      <%= f.select :product_id, options_for_select(@products), :class => "form-control" %>
    </div>
  </div> 

  <div class="form-group">
    <label for="quantity" class="col-sm-2 control-label">Quantity</label>
    <div class="col-sm-3">
      <div class="input-group">
        <%= f.text_field :quantity, :placeholder => "Quantity", :class => "form-control" %>
        <div class="input-group-addon">kg</div>
      </div>
    </div>
  </div>  

  <div class="form-group">
    <label for="quantity" class="col-sm-2 control-label">Total Price</label>
    <div class="col-sm-3">
      <div class="input-group">
        <div class="input-group-addon">Rp</div>
        <%= f.text_field :total_price, :placeholder => "Amount", :class => "form-control" %>
        <div class="input-group-addon">.00</div>
      </div>
    </div>
  </div>  

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-12">
      <%= f.submit 'Save', :class => "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1 class="page-header">Edit Sales</h1>
<%= render 'sales/form', :url => sale_path %>

app/views/sales/index.html.erb
<h1 class="page-header">Sale</h1>

<div class="form-group">
  <div class="col-sm-offset-1 col-sm-10">
    <%= link_to 'Add <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>'.html_safe, new_sale_path, :class => "btn btn-default" %>
    
    <div class="col-lg-4">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Search for...">
        <span class="input-group-btn">
          <button class="btn btn-default" type="button">
            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
          </button>
        </span>
      </div><!-- /input-group -->
    </div>

  </div>      
</div>
<div class="clearfix"></div>
<div class="table-responsive">
  <table class="table table-bordered">
    <caption></caption>
    <thead>
      <tr>
        <th>ID</th>
        <th>Date</th>
        <th>Product Name</th>
        <th>Customer Name</th>
        <th>Quantity</th>
        <th>&nbsp;</th>
      </tr>
    </thead>
    <tbody>
      <% @sales.each do |sale| %>
        <tr>
          <td><%= sale.id %></td>
          <td><%= sale.date.strftime("%d-%m-%Y") %></td>
          <td><%= sale.product.name %></td>
          <td><%= sale.customer.name %></td>
          <td><%= sale.quantity %></td>
          <td>
            <%= link_to "Update", edit_sale_path(sale) %>
            &nbsp
            <a href="">Delete</a>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/sales/new.html.erb
<h1 class="page-header">Add Sales</h1>
<%= render 'sales/form', :url => sales_path %>

app/views/suppliers/_form.html.erb
<%= form_for @supplier, :url => url, :html => {:class => "form-horizontal col-sm-12 col-sm-offset-1"} do |f| %>
<br><br>
  <div class="form-group">
    <label for="supplier_name" class="col-sm-2 control-label">Supplier Name</label>
    <div class="col-sm-3">
      <%= f.text_field :name, :placeholder => "Enter Supplier Name", :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label for="quantity" class="col-sm-2 control-label">Address</label>
    <div class="col-sm-3">
      <%= f.text_field :address, :placeholder => "Enter Supplier Address", :class => "form-control" %>
    </div>
  </div> 

  <div class="form-group">
    <label for="quantity" class="col-sm-2 control-label">Phone</label>
    <div class="col-sm-3">
      <%= f.text_field :phone, :placeholder => "Enter Supplier Phone", :class => "form-control" %>
    </div>
  </div>  

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-12">
      <%= f.submit 'Save', :class => "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/suppliers/edit.html.erb
<h1 class="page-header">Edit Supplier</h1>
<%= render 'suppliers/form', :url => supplier_path %>

app/views/suppliers/index.html.erb
<h1 class="page-header">Supplier</h1>

<div class="form-group">
  <div class="col-sm-offset-1 col-sm-10">
    <%= link_to 'Add <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>'.html_safe, new_supplier_path, :class => "btn btn-default" %>
    
    <div class="col-lg-4">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Search for...">
        <span class="input-group-btn">
          <button class="btn btn-default" type="button">
            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
          </button>
        </span>
      </div><!-- /input-group -->
    </div>

  </div>      
</div>
<div class="clearfix"></div>
<div class="table-responsive">
  <table class="table table-bordered">
    <caption></caption>
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Address</th>
        <th>Phone</th>
        <th>&nbsp;</th>
      </tr>
    </thead>
    <tbody>
      <% @suppliers.each do |supplier| %>
        <tr>
          <td><%= supplier.id %></td>
          <td><%= supplier.name %></td>
          <td><%= supplier.address %></td>
          <td><%= supplier.phone %></td>
          <td>
            <%= link_to "Update", edit_supplier_path(supplier) %>
            &nbsp
            <a href="">Delete</a>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/suppliers/new.html.erb
<h1 class="page-header">Add Supplier</h1>
<%= render 'suppliers/form', :url => suppliers_path %>