config/routes.rb
Xyz::Application.routes.draw do
  devise_for :users

  root 'homes#index'

  resources :homes
  resources :products
  resources :resources
  resources :customers
  resources :suppliers
  resources :sales

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :sales
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :product
  belongs_to :resource
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :ingredients
  has_many :resources, :through => :ingredients
  has_many :sales
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  has_many :ingredients
  has_many :products, :through => :ingredients
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :customer
  belongs_to :product
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @customers = Customer.all
  end

  def new
    @customer = Customer.new
  end

  def create    
    customer = Customer.new(customer_params)

    if customer.save
      notice = "Customer berhasil di buat."
    else
      notice = "Customer gagal di buat. Hubungi administrator."
    end
    redirect_to customers_path, :notice => notice
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    customer = Customer.find(params[:id])

    if customer.update_attributes(customer_params)
      notice = "customer berhasil di update."
    else
      notice = "customer gagal di update. Hubungi administrator."
    end
    redirect_to customers_path, :notice => notice
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :address, :phone)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
    @resources = Resource.all
  end

  def create
    product = Product.new(product_params)

    if product.save
      if params[:ingredients]
        params[:ingredients].each do |key, data|
          if data[:name]
            ingredient = Ingredient.new
            ingredient.product_id = product.id
            ingredient.resource_id = key
            ingredient.rate_percent = data[:rate_percent]
            ingredient.save
          end
        end
      end
      notice = "Product berhasil di buat."
    else
      notice = "Product gagal di buat. Hubungi administrator."
    end
    redirect_to products_path, :notice => notice
  end

  def edit
    @product = Product.find(params[:id])
    @resources = Resource.all
  end

  def update
    product = Product.find(params[:id])

    if product.update_attributes(product_params)
      notice = "Product berhasil di update."
    else
      notice = "Product gagal di update. Hubungi administrator."
    end
    redirect_to products_path, :notice => notice
  end


  private

  def product_params
    params.require(:product).permit(:name, :quantity, :price)
  end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @resources = Resource.all
  end

  def new
    @resource = Resource.new
  end

  def create    
    resource = Resource.new(resource_params)

    if resource.save
      notice = "Resource berhasil di buat."
    else
      notice = "Resource gagal di buat. Hubungi administrator."
    end
    redirect_to resources_path, :notice => notice
  end

  def edit
    @resource = Resource.find(params[:id])
  end

  def update
    resource = Resource.find(params[:id])

    if resource.update_attributes(resource_params)
      notice = "Resource berhasil di update."
    else
      notice = "Resource gagal di update. Hubungi administrator."
    end
    redirect_to resources_path, :notice => notice
  end

  private

  def resource_params
    params.require(:resource).permit(:name, :quantity)
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @sales = Sale.all
  end

  def new
    @sale = Sale.new
    @products = Product.all.collect{|x|[x.name, x.id]}
    @customers = Customer.all.collect{|x|[x.name, x.id]}
  end

  def create    
    sale = Sale.new(sale_params)

    if sale.save
      sale.product.update_attribute('quantity', (sale.product.quantity - sale.quantity))
      notice = "Sale berhasil di buat."
    else
      notice = "Sale gagal di buat. Hubungi administrator."
    end
    redirect_to sales_path, :notice => notice
  end

  def edit
    @sale = Sale.find(params[:id])
  end

  def update
    sale = Sale.find(params[:id])

    if sale.update_attributes(sale_params)
      notice = "Sale berhasil di update."
    else
      notice = "Sale gagal di update. Hubungi administrator."
    end
    redirect_to sales_path, :notice => notice
  end

  private

  def sale_params
    params.require(:sale).permit(:product_id, :customer_id, :date, :quantity, :total_price)
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @suppliers = Supplier.all
  end

  def new
    @supplier = Supplier.new
  end

  def create    
    supplier = Supplier.new(supplier_params)

    if supplier.save
      notice = "Supplier berhasil di buat."
    else
      notice = "Supplier gagal di buat. Hubungi administrator."
    end
    redirect_to suppliers_path, :notice => notice
  end

  def edit
    @supplier = Supplier.find(params[:id])
  end

  def update
    supplier = Supplier.find(params[:id])

    if supplier.update_attributes(supplier_params)
      notice = "Supplier berhasil di update."
    else
      notice = "Supplier gagal di update. Hubungi administrator."
    end
    redirect_to suppliers_path, :notice => notice
  end

  private

  def supplier_params
    params.require(:supplier).permit(:name, :address, :phone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def link_helper(name, control)
    name == control ? flag = true : flag = false

    if flag
      return 'active'
    else
      return ''
    end
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>>PT XYZ</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'dashboard' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'bootstrap' %>
  <%= csrf_meta_tag %>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
        </button>
        <a class="navbar-brand" href="index.html">Sistem Inventory PT XYZ</a>
      </div>
      <% if current_user %>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
        
            <li class="dropdown">
              <a class="dropdown-toggle" role="button" data-toggle="dropdown" href="#">
              <i class="glyphicon glyphicon-user"></i> Welcome, <%= (current_user.first_name.present? ? current_user.first_name : "Admin") rescue "Admin" %></span></a>
              <ul id="g-account-menu" class="dropdown-menu" role="menu">
                <li><a href="#">My Profile</a></li>
                <li><%= link_to "<i class='glyphicon glyphicon-lock'></i> Logout".html_safe, destroy_user_session_path %></li>
              </ul>
            </li>
          </ul>
        </div>
      <% end %>
    </div>
  </nav>
    
  <%= render 'layouts/messages' %>
    
  <div style="margin-top: 50px;">
    <% unless params[:controller] == "devise/sessions" && params[:action] == "new" %>
      <div class="container-fluid">
        <div class="row">
          <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
              <li class="<%= link_helper('homes', params[:controller]) %>">
                <%= link_to "Company Profile", root_url %>
              </li>
              <li class="<%= link_helper('products', params[:controller]) %>">
                <%= link_to "Product", products_path %>
              <li class="<%= link_helper('resources', params[:controller]) %>">
                <%= link_to "Resource", resources_path %>
              </li>
              <li class="<%= link_helper('sales', params[:controller]) %>">
                <%= link_to "Sales", sales_path %>
              </li>
            </ul>
            <ul class="nav nav-sidebar">
              <li class="<%= link_helper('customers', params[:controller]) %> <%= link_helper('suppliers', params[:controller]) %>">
                <a href="#demo4" data-toggle="collapse" data-parent="#MainMenu">Master Data</a>
                  <div class="collapse" id="demo4">
                    <%= link_to "Data Customer", customers_path, :class => "list-group-item" %>
                    <%= link_to "Data Supplier", suppliers_path, :class => "list-group-item" %>
                  </div>
              </li>
              <li><a href="">Laporan</a></li>         
            </ul>
          </div>
        </div>
      </div>    
      
      <div class="clearfix"></div>
      <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <%= yield %>
      </div>
    <% else %>
      <%= yield %>
    <% end %>
  </div>
</body>
</html>

app/views/resources/_form.html.erb
<%= form_for @resource, :url => url, :html => {:class => "form-horizontal col-sm-12 col-sm-offset-1"} do |f| %>
<br><br>
  <div class="form-group">
    <label for="resource_name" class="col-sm-2 control-label">Resource Name</label>
    <div class="col-sm-3">
      <%= f.text_field :name, :placeholder => "Enter Resource Name", :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label for="quantity" class="col-sm-2 control-label">Quantity</label>
    <div class="col-sm-3">
      <%= f.text_field :quantity, :placeholder => "Enter Resource Quantity per KG", :class => "form-control" %>
    </div>
  </div>  

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-12">
      <%= f.submit 'Save', :class => "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1 class="page-header">Edit Resource</h1>
<%= render 'resources/form', :url => resource_path %>

app/views/resources/index.html.erb
<h1 class="page-header">Resource</h1>

<div class="form-group">
  <div class="col-sm-offset-1 col-sm-10">
    <%= link_to 'Add <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>'.html_safe, new_resource_path, :class => "btn btn-default" %>
    
    <div class="col-lg-4">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Search for...">
        <span class="input-group-btn">
          <button class="btn btn-default" type="button">
            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
          </button>
        </span>
      </div><!-- /input-group -->
    </div>

  </div>      
</div>
<div class="clearfix"></div>
<div class="table-responsive">
  <table class="table table-bordered">
    <caption></caption>
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Quantity</th>
        <th>&nbsp;</th>
      </tr>
    </thead>
    <tbody>
      <% @resources.each do |resource| %>
        <tr>
          <td><%= resource.id %></td>
          <td><%= resource.name %></td>
          <td><%= resource.quantity %></td>
          <td>
            <%= link_to "Update", edit_resource_path(resource) %>
            &nbsp
            <a href="">Delete</a>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/resources/new.html.erb
<h1 class="page-header">Add Resource</h1>
<%= render 'resources/form', :url => resources_path %>